<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btnGoogle</name>
   <tag></tag>
   <elementGuidId>094a54cb-083b-4ce8-b9a5-924bb6e3b17a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;content&quot;]/div/div/div[1]/div[2]/div[2]/div/div/div/div[2]/div[3]/div[2]/button</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <value>//*[@id=&quot;content&quot;]/div/div/div[1]/div[2]/div[2]/div/div/div/div[2]/div[3]/div[2]/button</value>
   </webElementXpaths>
</WebElementEntity>
