<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>hitNews</name>
   <tag></tag>
   <elementGuidId>bbaefe78-fb9a-4bc0-9a41-26a4a7a290d2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//a[@href='/@kumparannews/jokowi-tunjuk-andika-perkasa-jadi-ksad-pengganti-mulyono-1542839764888425501?ref=trenstory']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//a[@href='/@kumparannews/jokowi-tunjuk-andika-perkasa-jadi-ksad-pengganti-mulyono-1542839764888425501?ref=trenstory']</value>
   </webElementProperties>
</WebElementEntity>
